---    
  - name: 'Upgrade all packages to the latest version'
    apt:
      name: "*"
      state: latest
    become: true

  - name: 'Installing php and nginx dependencies'
    apt:
      name: "{{item}}"
      state: latest
    become: true
    loop: 
      - nginx
      - php7.2-fpm
      - php-ssh2
      - python-mysqldb
      - php7.2-mysql