# roles/mysql/tasks/main.yml
  - name: 'Upgrade all packages to the latest version'
    apt:
      name: "*"
      state: latest
    become: true

  - name: 'Install dependecy packages'
    apt:
      name: "{{item}}"
      state: latest
    become: true
    loop: 
      - mysql-server

  - name: 'Install python pip'
    apt:
      name: python3-pip
      state: present
    become: true

  - name: 'Install PyMySQL from pip'
    pip:
      name: pymysql
      state: present
    become: true

  - name: 'Create MySQL database'
    mysql_db: 
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: '{{www_db}}'
      state: present
    become: true

  - name: 'Create MySQL User'
    mysql_user: 
      login_unix_socket: /var/run/mysqld/mysqld.sock
      host: '%'
      name: '{{www_user}}'
      password: '{{www_userpass}}'
      priv: '{{www_db}}.*:ALL'
      state: present
    become: true
    no_log: true
    
  - name: 'Allowing MySQL remote connections'     
    replace:
      path: '/etc/mysql/mysql.conf.d/mysqld.cnf'
      regexp: "{{ item.regex }}"
      replace: "{{ item.value }}"
    with_items:
      - { regex: '127.0.0.1', value: '0.0.0.0'}
    become: true
    notify:
      - restart mysql