---    
  - name: 'Upgrade all packages to the latest version'
    apt:
      name: "*"
      state: latest
    become: true

  - name: 'Installing php and apache dependencies'
    apt:
      name: "{{item}}"
      state: latest
    become: true
    loop: 
      - php7.2
      - apache2
      - libapache2-mod-php7.2
      - php7.2-gd
      - php-ssh2
      - python-mysqldb
      - php7.2-mysql