---
  - name: 'Download wordpress files'
    get_url:
     url: 'https://wordpress.org/latest.tar.gz'
     dest: '/tmp/wordpress.tar.gz'

  - name: 'Wordpress unzipping'
    unarchive:
      src: '/tmp/wordpress.tar.gz'
      dest: /var/www/
      remote_src: yes
    become: true

  - name: 'Copying wordpress configuration file (wp-config.php)'
    copy:
      src: '{{wordpress_dir}}/wp-config-sample.php'
      dest: '{{wordpress_dir}}/wp-config.php'
      force: no
      remote_src: yes
    become: true

  - name: 'Modifying wordpress configuratin file (wp-config.php) '     
    replace:
      path: '{{wordpress_dir}}/wp-config.php'
      regexp: "{{ item.regex }}"
      replace: "{{ item.value }}"
    with_items:
      - { regex: 'database_name_here', value: '{{wordpress_db}}'}
      - { regex: 'username_here', value: '{{wordpress_user}}'}
      - { regex: 'password_here', value: '{{wordpress_userpass}}'}
      - { regex: 'localhost', value: '{{wordpress_dbip}}'}
    become: true

  - name: 'Configuring Apache with Wordpress'
    template:
      src: 'templates/000-default.conf.j2'
      dest: '/etc/apache2/sites-available/000-default.conf'
    become: true   
    notify:
      - restart apache          